# generated by datamodel-codegen:
#   filename:  any.json
#   timestamp: 2023-06-29T13:06:33+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Extra, Field

from . import placement


class IAny(BaseModel):
    class Config:
        extra = Extra.forbid

    Shape: str = Field(..., description='The BREP string of the shape')
    Placement: Optional[placement.Model] = None
