# generated by datamodel-codegen:
#   filename:  placement.json
#   timestamp: 2023-06-29T13:06:33+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra, Field


class Model(BaseModel):
    class Config:
        extra = Extra.forbid

    Position: List[float] = Field(..., description='Position of the Placement')
    Axis: List[float] = Field(..., description='Axis of the Placement')
    Angle: float = Field(..., description='Angle of the Placement')
